web: gunicorn --bind 0.0.0.0:5000 --workers 3 app:app
worker: celery -A tasks worker --loglevel=info --concurrency=12
flower: celery flower -A tasks --port=5555 --broker=redis://redis_test:6379/0
celery-beat: celery -A tasks beat -s /var/run/celerybeat-schedule --loglevel=info