worker: celery -A tasks worker --loglevel=info
flower: celery flower -A tasks --port=5555 --broker=redis://redis_test:6379/0
celery-beat: celery -A tasks beat -s /var/run/celerybeat-schedule --loglevel=info